baseURL = 'https://kinjileslie.pstat.ucsb.edu/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'risotto'

# Error handling and menu automation
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main"

[pagination]
  pagerSize = 3

[params]
  noindex = false

[params.theme]
  palette = "base16-dark"

[params.about]
  title = "risotto"
  description = "A [hugo](https://gohugo.io) theme inspired by terminal ricing."
  logo = "🍚"

[[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/kinjileslie"

[[params.socialLinks]]
  icon = "fa-solid fa-envelope"
  title = "Email"
  url = "mailto:kinji@pstat.ucsb.edu"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
